# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./battery-ui
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./battery-ui/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
      - name: Run Tests
        run: npm run test
      - name: Build
        run: npm run build
  frontend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./battery-ui
    needs: [frontend-testing]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image and Tag
        env:
          IMAGE_NAME: daq-battery-ui
          VERSION: "prod-1.0.${{ github.run_number }}"
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kuroson/daq-battery-ui-fe
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
